### ISSUE TITLE
.git directory install error 

### ISSUE THREAD

**Issue by AhnSeongHyun** [AhnSeongHyun/project_template#1]
Typing project name :doogpeople
what is project name? is"doogpeople".
Rename project to  "doogpeople"...
Traceback (most recent call last):
  File "install.py", line 22, in <module>
    shutil.move(current_dir, dest_dir)
  File "C:\Python27\lib\shutil.py", line 299, in move
    rmtree(src)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] : 'C:\workspace\company\project_template\.git\objects\1d\86017da33122afcdc86656e00aaa196481ea3a'

**Comment by AhnSeongHyun** [comment]
use administrative run for cmd.
