### ISSUE TITLE
windows env

### ISSUE THREAD

**Issue by AhnSeongHyun** [AhnSeongHyun/project_template#4]
Typing project name :mt
what is project name? is"mt".
Rename project to  "mt"...
Traceback (most recent call last):
  File "install.py", line 30, in <module>
    shutil.move(current_dir, dest_dir)
  File "C:\Python27\lib\shutil.py", line 299, in move
    rmtree(src)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] : 'C:\workspace\github\project_template\.git\objects\10\08be781d
0a4e1e4f13e85a4f2452d1caecd212'

**Comment by AhnSeongHyun** [comment]
it is windows admin issue.
